version: "3.9"

services:

  database:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: angelo_lamonaca
      MYSQL_DATABASE: dicom-viewer
    ports:
      - "3306:3306"
    networks:
      - default

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "angelo_lamonaca/mini-dicom-viewer-backend"
    ports:
      - "3301:3301"
    depends_on:
      - database
    command: bash -c "./wait-for-it.sh database:3306 && npx sequelize-cli db:migrate && node src/index.js"
    networks:
      - default

  fixtures:
    build: ./fixtures
    image: "angelo_lamonaca/mini-dicom-viewer-fixtures"
    depends_on:
      - database
    command: bash -c "./wait-for-it.sh backend:3301 && sleep 15 && python main.py"
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "angelo_lamonaca/mini-dicom-viewer-frontend"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default: